services:
  - type: web
    name: antonelli-dashboard
    runtime: docker
    plan: free
    dockerfilePath: dae_service/Dockerfile
    dockerContext: dae_service
    envVars:
      - key: PLANT_NAME
        value: "Antonelli"
      - key: SOLAX_CLOUD_EMAIL
        sync: false
      - key: SOLAX_CLOUD_PASSWORD
        sync: false
      - key: SOLAX_SITE_ID
        value: "1613166446950068231"
      - key: ZEUS_ENABLED
        value: "true"
      - key: DATABASE_URL
        sync: false
